security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    bruno: { password: BrnCsc*UOAIO=BrunoCascio, roles: [ 'ROLE_SUPER_ADMIN'] }
                    beatriz: { password: btrzgrr, roles: [ 'ROLE_ADMIN'] }
                    rosa: { password: mrrsmss, roles: [ 'ROLE_ADMIN'] }
                    laura: { password: lrsgsmnd, roles: [ 'ROLE_ADMIN'] }
                    carmen: { password: mrdlcrmnmtt, roles: [ 'ROLE_ADMIN'] }
                    graciela: { password: grclndrn, roles: [ 'ROLE_ADMIN'] }
                    patricia: { password: ptrcgnzlzgrz, roles: [ 'ROLE_ADMIN'] }
                    fede: { password: fdrcprz, roles: [ 'ROLE_ADMIN'] }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            #pattern:    ^/demo/secured/
            pattern:    ^/(admin|buscar)
            #form_login:
            #   check_path: _security_check
            #   login_path: _demo_login
            #logout:
            #    path:   _demo_logout
            #    target: _demo
            anonymous: ~
            http_basic:
                realm: "Sitio Administradoras"
            stateless:  true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }